name: Deploy QA Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade ibm-watsonx-ai
          pip install -r requirements.txt

      - name: Run QA Bot
        run: |
          python qa_bot.py
