name: Deploy QA Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check installed ibm-watsonx-ai version
        run: pip show ibm-watsonx-ai

      - name: List files in ibm_watsonx_ai/foundation_models
        run: |
          ls -l /opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/ibm_watsonx_ai/foundation_models/

      - name: Run QA Bot
        run: |
          python qa_bot.py
